[variables]
CI = "false"
GENERATE_SOURCEMAP = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build"
]

[start]
cmd = "npx serve -s build -l $PORT"