[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[build]
buildCommand = """
npm ci && 
npm run build
"""

[deploy]
startCommand = "npx serve -s build -l $PORT"

[variables]
PORT = "3000"
CI = "false"
GENERATE_SOURCEMAP = "false"