[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "backend/"

[services.build]
buildCommand = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"

[[services]]
name = "frontend" 
source = "frontend/"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build -l $PORT"

[services.variables]
PORT = "3000"
CI = "false"