[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100

[build]
buildCommand = """
pip install --no-cache-dir -r requirements.txt && 
python -m spacy download en_core_web_sm
"""

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"
PYTHONPATH = "/app"